name: "2. Continuous Deployment (Release Preview)"

on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+-preview*"

jobs:
  build-and-pack:
    uses: ./.github/workflows/cd-build-test-pack.yml
    with:
      version: ${{ github.ref_name }}
      configuration: Release

  publish:
    needs: build-and-pack
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Push to NuGet
        run: dotnet nuget push nuget-packages/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
